chive(1)

# NAME

chive - a file variant switcher

# SYNOPSIS

chive [_options_] [_targets_ | _variants_]...

# Options

*-t, --target* _TARGET_...
	adds targets

*-v, --variant* [_TARGET_] _VARIANT_ ...
	adds variants

*-e, --edit* [_TARGET_]
	edits targets & variants

*-d, --delete*
	deletes targets & variants

# AUTHORS

Maintained by Jason Phan <td.jasonphan@gmail.com>. For more information about
chive development, see https://github.com/bl0nd/chive.
